apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-deployment
  labels:
    app: ip-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip-app
  template:
    metadata:
      labels:
        app: ip-app
    spec:
      containers:
      - name: ip-app
        image: nikhils9/myapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
   name: my-ipapp-svc
spec:
    type: NodePort
    selector:
        app: ip-app
    ports:
       - name: http
         nodePort: 30099
         port: 8086
         targetPort: 80
