apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tom-deployment
  labels:
    app: my-tom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-tom
  template:
    metadata:
      labels:
        app: my-tom
    spec:
      containers:
      - name: my-tom
        image: nikhils9/tomcat:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
   name: my-ipapp-svc
spec:
    type: NodePort
    selector:
        app: my-tom
    ports:
       - name: http
         nodePort: 30199
         port: 8095
         targetPort: 8080
